// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recipe/recipe.proto

package recipe

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Ingredient struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ingredient) Reset()         { *m = Ingredient{} }
func (m *Ingredient) String() string { return proto.CompactTextString(m) }
func (*Ingredient) ProtoMessage()    {}
func (*Ingredient) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_e39866176f5de4e4, []int{0}
}
func (m *Ingredient) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ingredient.Unmarshal(m, b)
}
func (m *Ingredient) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ingredient.Marshal(b, m, deterministic)
}
func (dst *Ingredient) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ingredient.Merge(dst, src)
}
func (m *Ingredient) XXX_Size() int {
	return xxx_messageInfo_Ingredient.Size(m)
}
func (m *Ingredient) XXX_DiscardUnknown() {
	xxx_messageInfo_Ingredient.DiscardUnknown(m)
}

var xxx_messageInfo_Ingredient proto.InternalMessageInfo

func (m *Ingredient) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Recipe struct {
	Name                 string        `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Ingredients          []*Ingredient `protobuf:"bytes,2,rep,name=Ingredients,proto3" json:"Ingredients,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_e39866176f5de4e4, []int{1}
}
func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (dst *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(dst, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipe) GetIngredients() []*Ingredient {
	if m != nil {
		return m.Ingredients
	}
	return nil
}

type GetRecipesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRecipesRequest) Reset()         { *m = GetRecipesRequest{} }
func (m *GetRecipesRequest) String() string { return proto.CompactTextString(m) }
func (*GetRecipesRequest) ProtoMessage()    {}
func (*GetRecipesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_e39866176f5de4e4, []int{2}
}
func (m *GetRecipesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipesRequest.Unmarshal(m, b)
}
func (m *GetRecipesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipesRequest.Marshal(b, m, deterministic)
}
func (dst *GetRecipesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipesRequest.Merge(dst, src)
}
func (m *GetRecipesRequest) XXX_Size() int {
	return xxx_messageInfo_GetRecipesRequest.Size(m)
}
func (m *GetRecipesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipesRequest proto.InternalMessageInfo

type GetRecipesResponse struct {
	Recipes              []*Recipe `protobuf:"bytes,1,rep,name=Recipes,proto3" json:"Recipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetRecipesResponse) Reset()         { *m = GetRecipesResponse{} }
func (m *GetRecipesResponse) String() string { return proto.CompactTextString(m) }
func (*GetRecipesResponse) ProtoMessage()    {}
func (*GetRecipesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_recipe_e39866176f5de4e4, []int{3}
}
func (m *GetRecipesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRecipesResponse.Unmarshal(m, b)
}
func (m *GetRecipesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRecipesResponse.Marshal(b, m, deterministic)
}
func (dst *GetRecipesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRecipesResponse.Merge(dst, src)
}
func (m *GetRecipesResponse) XXX_Size() int {
	return xxx_messageInfo_GetRecipesResponse.Size(m)
}
func (m *GetRecipesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRecipesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRecipesResponse proto.InternalMessageInfo

func (m *GetRecipesResponse) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func init() {
	proto.RegisterType((*Ingredient)(nil), "Ingredient")
	proto.RegisterType((*Recipe)(nil), "Recipe")
	proto.RegisterType((*GetRecipesRequest)(nil), "GetRecipesRequest")
	proto.RegisterType((*GetRecipesResponse)(nil), "GetRecipesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecipeServiceClient is the client API for RecipeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecipeServiceClient interface {
	GetRecipes(ctx context.Context, in *GetRecipesRequest, opts ...grpc.CallOption) (*GetRecipesResponse, error)
}

type recipeServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecipeServiceClient(cc *grpc.ClientConn) RecipeServiceClient {
	return &recipeServiceClient{cc}
}

func (c *recipeServiceClient) GetRecipes(ctx context.Context, in *GetRecipesRequest, opts ...grpc.CallOption) (*GetRecipesResponse, error) {
	out := new(GetRecipesResponse)
	err := c.cc.Invoke(ctx, "/RecipeService/GetRecipes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecipeServiceServer is the server API for RecipeService service.
type RecipeServiceServer interface {
	GetRecipes(context.Context, *GetRecipesRequest) (*GetRecipesResponse, error)
}

func RegisterRecipeServiceServer(s *grpc.Server, srv RecipeServiceServer) {
	s.RegisterService(&_RecipeService_serviceDesc, srv)
}

func _RecipeService_GetRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecipesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecipeServiceServer).GetRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RecipeService/GetRecipes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecipeServiceServer).GetRecipes(ctx, req.(*GetRecipesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecipeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RecipeService",
	HandlerType: (*RecipeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRecipes",
			Handler:    _RecipeService_GetRecipes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recipe/recipe.proto",
}

func init() { proto.RegisterFile("recipe/recipe.proto", fileDescriptor_recipe_e39866176f5de4e4) }

var fileDescriptor_recipe_e39866176f5de4e4 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x4a, 0x4d, 0xce,
	0x2c, 0x48, 0xd5, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0x0a, 0x5c, 0x5c, 0x9e,
	0x79, 0xe9, 0x45, 0xa9, 0x29, 0x99, 0xa9, 0x79, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x7e, 0x89, 0xb9,
	0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x37, 0x17, 0x5b, 0x10, 0x58,
	0x07, 0x36, 0x59, 0x21, 0x5d, 0x2e, 0x6e, 0x84, 0xfe, 0x62, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e,
	0x23, 0x6e, 0x3d, 0x84, 0x58, 0x10, 0xb2, 0xbc, 0x92, 0x30, 0x97, 0xa0, 0x7b, 0x6a, 0x09, 0xc4,
	0xbc, 0xe2, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x25, 0x73, 0x2e, 0x21, 0x64, 0xc1, 0xe2,
	0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x45, 0x2e, 0x76, 0xa8, 0x90, 0x04, 0x23, 0xd8, 0x54, 0x76,
	0x3d, 0x08, 0x3f, 0x08, 0x26, 0x6e, 0xe4, 0xc6, 0xc5, 0x0b, 0x61, 0x06, 0xa7, 0x16, 0x95, 0x65,
	0x26, 0xa7, 0x0a, 0x99, 0x72, 0x71, 0x21, 0x4c, 0x12, 0x12, 0xd2, 0xc3, 0xb0, 0x4b, 0x4a, 0x58,
	0x0f, 0xd3, 0xaa, 0x24, 0x36, 0x70, 0x58, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xdf,
	0xed, 0xb8, 0x22, 0x01, 0x00, 0x00,
}
